### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by withtheprettygang**

### CODE REVIEW

**Comment by withtheprettygang** [comment]
wekesa hallo. look ive lost my phone today p;ease send me kamash number and
also please send me your number im trying to get a new phone then we'll
link up

**Comment by salawekesa** [comment]
sorry bro,
Mine -> +254 707080977
Kamash -> 254 704 166280

**Comment by withtheprettygang** [comment]
wassup,how you doing? hows the going, hope you well . where are you guys
with the project

**Comment by salawekesa** [comment]
hello bro, we are only focusing on the django project for now, still
creating the views and models

**Comment by withtheprettygang** [comment]
damn man are we gonna do this or what

**Comment by withtheprettygang** [comment]
wassup ,hows tingz hope you hows the project coming up,.and when we
supposed to make final submissions

**Comment by withtheprettygang** [comment]
wekesa hi, whens the final date for submission of our projects

**Comment by salawekesa** [comment]
it has not yet been set

**Comment by withtheprettygang** [comment]
Ok, thanks for the update.

**Pull request merged**
